.TH "dlre_xzv2azel.f" 3 "Tue Sep 4 2012" "Diviner pipes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dlre_xzv2azel.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBdlre_xzv2azel\fP (SCX, SCZ, VEC, AZDEG, ELDEG, SUCCSS)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine dlre_xzv2azel (double precision, dimension    ( 3 )SCX, double precision, dimension    ( 3 )SCZ, double precision, dimension    ( 3 )VEC, double precisionAZDEG, double precisionELDEG, logicalSUCCSS)"

.PP
Definition at line 3 of file dlre_xzv2azel\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Diviner pipes from the source code\&.
