.TH "gridsetup.f" 3 "Tue Sep 4 2012" "Diviner pipes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gridsetup.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBgridsetup\fP (voxsize, ntri, tri, gridmin, gridmax, ngrid)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine gridsetup (real*4, dimension(3)voxsize, integer*4ntri, real*4, dimension(3,3,ntri)tri, real*4, dimension(3)gridmin, real*4, dimension(3)gridmax, integer*4, dimension(3)ngrid)"

.PP
Definition at line 1 of file gridsetup\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Diviner pipes from the source code\&.
