.TH "p3dcrosstrackplanning2.f" 3 "Tue Sep 4 2012" "Diviner pipes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p3dcrosstrackplanning2.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBctricna\fP (t, tc, tn, tarea)"
.br
.ti -1c
.RI "program \fBp3crosstrackplanning\fP"
.br
.ti -1c
.RI "subroutine \fBvecmatmult\fP (a1, a2, a3, m, v1, v2, v3)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine ctricna (real*4, dimension(3,3)t, real*4, dimension(3)tc, real*4, dimension(3)tn, real*4tarea)"

.PP
Definition at line 1050 of file p3dcrosstrackplanning2\&.f\&.
.SS "program p3crosstrackplanning ()"

.PP
Definition at line 48 of file p3dcrosstrackplanning2\&.f\&.
.SS "subroutine vecmatmult (real*8a1, real*8a2, real*8a3, real*8, dimension(3,3)m, real*8v1, real*8v2, real*8v3)"

.PP
Definition at line 1080 of file p3dcrosstrackplanning2\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Diviner pipes from the source code\&.
