.TH "p3dlonlatalt_09.f" 3 "Tue Sep 4 2012" "Diviner pipes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p3dlonlatalt_09.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBctricna\fP (t, tc, tn, tarea)"
.br
.ti -1c
.RI "program \fBp3dgeom\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine ctricna (real*4, dimension(3,3)t, real*4, dimension(3)tc, real*4, dimension(3)tn, real*4tarea)"

.PP
Definition at line 345 of file p3dlonlatalt_09\&.f\&.
.SS "program p3dgeom ()"

.PP
Definition at line 34 of file p3dlonlatalt_09\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Diviner pipes from the source code\&.
