.TH "parith.f" 3 "Tue Sep 4 2012" "Diviner pipes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parith.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBparith\fP"
.br
.ti -1c
.RI "subroutine \fBwritedesheader\fP (lunit)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "program parith ()"

.PP
Definition at line 60 of file parith\&.f\&.
.SS "subroutine writedesheader (integerlunit)"

.PP
Definition at line 312 of file parith\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Diviner pipes from the source code\&.
