.TH "pbin1d.f" 3 "Tue Sep 4 2012" "Diviner pipes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pbin1d.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBmakepbin1d\fP (nx, dx, xmin, xmax, xlen, sum, sumsq, cnt, avg, sigma, min, max)"
.br
.ti -1c
.RI "program \fBpbin1d\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine makepbin1d (integernx, real*8dx, real*8xmin, real*8xmax, real*8xlen, real*8, dimension(nx)sum, real*8, dimension(nx)sumsq, real*8, dimension(nx)cnt, real*8, dimension(nx)avg, real*8, dimension(nx)sigma, real*8, dimension(nx)min, real*8, dimension(nx)max)"

.PP
Definition at line 110 of file pbin1d\&.f\&.
.SS "program pbin1d ()"

.PP
Definition at line 34 of file pbin1d\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Diviner pipes from the source code\&.
