.TH "pbin2d.f" 3 "Tue Sep 4 2012" "Diviner pipes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pbin2d.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBmakepbin2d\fP (nx, dx, xmin, xmax, xlen, ny, dy, ymin, ymax, ylen, sum, sum1, sum2, cnt, cnt1, cnt2, avg, avg1, avg2)"
.br
.ti -1c
.RI "program \fBpbin2d\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine makepbin2d (integernx, real*8dx, real*8xmin, real*8xmax, real*8xlen, integerny, real*8dy, real*8ymin, real*8ymax, real*8ylen, real*8, dimension(nx,ny)sum, real*8, dimension(nx,ny)sum1, real*8, dimension(nx,ny)sum2, real*8, dimension(nx,ny)cnt, real*8, dimension(nx,ny)cnt1, real*8, dimension(nx,ny)cnt2, real*8, dimension(nx,ny)avg, real*8, dimension(nx,ny)avg1, real*8, dimension(nx,ny)avg2)"

.PP
Definition at line 134 of file pbin2d\&.f\&.
.SS "program pbin2d ()"

.PP
Definition at line 50 of file pbin2d\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Diviner pipes from the source code\&.
