.TH "pbin3dsparse.f" 3 "Tue Sep 4 2012" "Diviner pipes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pbin3dsparse.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBmakepbin3d\fP (nx, dx, xmin, xmax, xlen, ny, dy, ymin, ymax, ylen, nz, dz, zmin, zmax, zlen, sum, sumsq, cnt, avg, sigma, min, max, isparse, ititles, itable, iexclude, exclude)"
.br
.ti -1c
.RI "program \fBpbin3dsparse\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine makepbin3d (integernx, real*8dx, real*8xmin, real*8xmax, real*8xlen, integerny, real*8dy, real*8ymin, real*8ymax, real*8ylen, integernz, real*8dz, real*8zmin, real*8zmax, real*8zlen, real*8, dimension(nx,ny,nz)sum, real*8, dimension(nx,ny,nz)sumsq, real*8, dimension(nx,ny,nz)cnt, real*8, dimension(nx,ny,nz)avg, real*8, dimension(nx,ny,nz)sigma, real*8, dimension(nx,ny,nz)min, real*8, dimension(nx,ny,nz)max, integer*4isparse, integer*4ititles, integer*4itable, integer*4iexclude, real*8exclude)"

.PP
Definition at line 192 of file pbin3dsparse\&.f\&.
.SS "program pbin3dsparse ()"

.PP
Definition at line 59 of file pbin3dsparse\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Diviner pipes from the source code\&.
