.TH "pgetmodel_09.f" 3 "Tue Sep 4 2012" "Diviner pipes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pgetmodel_09.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBdfindy\fP (xx, yy, n, x, y)"
.br
.ti -1c
.RI "subroutine \fBdlocate\fP (xx, n, x, j)"
.br
.ti -1c
.RI "program \fBpgetmodel_09\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine dfindy (real*8, dimension(n)xx, real*8, dimension(n)yy, n, real*8x, real*8y)"

.PP
Definition at line 177 of file pgetmodel_09\&.f\&.
.SS "subroutine dlocate (real*8, dimension(n)xx, n, real*8x, j)"

.PP
Definition at line 206 of file pgetmodel_09\&.f\&.
.SS "program pgetmodel_09 ()"

.PP
Definition at line 27 of file pgetmodel_09\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Diviner pipes from the source code\&.
