.TH "pgetranges.f" 3 "Tue Sep 4 2012" "Diviner pipes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pgetranges.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBpgetranges\fP"
.br
.ti -1c
.RI "subroutine \fBsetrange\fP (value, min, max)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "program pgetranges ()"

.PP
Definition at line 26 of file pgetranges\&.f\&.
.SS "subroutine setrange (real*8value, real*8min, real*8max)"

.PP
Definition at line 153 of file pgetranges\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Diviner pipes from the source code\&.
