.TH "pitri2lonlatalt_10.f" 3 "Tue Sep 4 2012" "Diviner pipes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pitri2lonlatalt_10.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBctricna\fP (t, tc, tn, tarea)"
.br
.ti -1c
.RI "program \fBp3dgeom\fP"
.br
.ti -1c
.RI "subroutine \fBxyz2latlon\fP (x, y, z, r0, dlat, dlon, htri)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine ctricna (real*4, dimension(3,3)t, real*4, dimension(3)tc, real*4, dimension(3)tn, real*4tarea)"

.PP
Definition at line 190 of file pitri2lonlatalt_10\&.f\&.
.SS "program p3dgeom ()"

.PP
Definition at line 27 of file pitri2lonlatalt_10\&.f\&.
.SS "subroutine xyz2latlon (real*4x, real*4y, real*4z, real*4r0, real*4dlat, real*4dlon, real*4htri)"

.PP
Definition at line 169 of file pitri2lonlatalt_10\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Diviner pipes from the source code\&.
