.TH "pnadirangle.f" 3 "Tue Sep 4 2012" "Diviner pipes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pnadirangle.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBpnadirangle\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "program pnadirangle ()"

.PP
Definition at line 31 of file pnadirangle\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Diviner pipes from the source code\&.
