.TH "pread.f" 3 "Tue Sep 4 2012" "Diviner pipes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pread.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBpread\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "program pread ()"

.PP
Definition at line 35 of file pread\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Diviner pipes from the source code\&.
