.TH "psort.f" 3 "Tue Sep 4 2012" "Diviner pipes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
psort.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBpsort\fP"
.br
.ti -1c
.RI "subroutine \fBsortrx\fP (N, DATA, MYINDEX)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "program psort ()"

.PP
Definition at line 1 of file psort\&.f\&.
.SS "subroutine sortrx (integerN, real*8, dimension(n)DATA, integer, dimension(n)MYINDEX)"

.PP
Definition at line 122 of file psort\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Diviner pipes from the source code\&.
