.TH "pspolexy.f" 3 "Tue Sep 4 2012" "Diviner pipes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pspolexy.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBpspolexy\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "program pspolexy ()"

.PP
Definition at line 33 of file pspolexy\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Diviner pipes from the source code\&.
